openapi: 3.0.0
info:
  title: Mission Pizza API
  version: 1.0.0
paths:
  /menu:
    get:
      summary: Get the list of pizzas
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
  /order:
    post:
      summary: Place an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
      responses:
        '200':
          description: Order placed
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                  message:
                    type: string
  /order/{order_id}:
    get:
      summary: Track order status
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'

components:
  schemas:
    Pizza:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        size:
          type: string
        price:
          type: number
        order_id:
          type: string
